//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterOfMasterDesktop.svcMOM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcMOM.IMasterOfMasterSvc")]
    public interface IMasterOfMasterSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroDetalleResponse")]
        string InsertarMaestroDetalle(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroDetalleResponse")]
        System.Threading.Tasks.Task<string> InsertarMaestroDetalleAsync(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroDetalleResponse")]
        string ActualizarMaestroDetalle(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle, string pDescripcionAntigua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroDetalleResponse")]
        System.Threading.Tasks.Task<string> ActualizarMaestroDetalleAsync(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle, string pDescripcionAntigua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroDetalleResponse")]
        MasterOfMasterModels.cMaestrosDetalle[] ConsultarMaestroDetalle(long pIdMDetalle, long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroDetalle", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroDetalleResponse")]
        System.Threading.Tasks.Task<MasterOfMasterModels.cMaestrosDetalle[]> ConsultarMaestroDetalleAsync(long pIdMDetalle, long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroCabeceraResponse")]
        string InsertarMaestroCabecera(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/InsertarMaestroCabeceraResponse")]
        System.Threading.Tasks.Task<string> InsertarMaestroCabeceraAsync(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroCabeceraResponse")]
        string ActualizarMaestroCabecera(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera, string pDescripcionAntigua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ActualizarMaestroCabeceraResponse")]
        System.Threading.Tasks.Task<string> ActualizarMaestroCabeceraAsync(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera, string pDescripcionAntigua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroCabeceraResponse")]
        MasterOfMasterModels.cMaestrosCabecera[] ConsultarMaestroCabecera(long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroCabecera", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ConsultarMaestroCabeceraResponse")]
        System.Threading.Tasks.Task<MasterOfMasterModels.cMaestrosCabecera[]> ConsultarMaestroCabeceraAsync(long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/CrearTabla", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/CrearTablaResponse")]
        string CrearTabla(MasterOfMasterModels.Tabla MA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/CrearTabla", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/CrearTablaResponse")]
        System.Threading.Tasks.Task<string> CrearTablaAsync(MasterOfMasterModels.Tabla MA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ListarMAestrosAvanzados", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ListarMAestrosAvanzadosResponse")]
        MasterOfMasterModels.Tabla[] ListarMAestrosAvanzados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/ListarMAestrosAvanzados", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/ListarMAestrosAvanzadosResponse")]
        System.Threading.Tasks.Task<MasterOfMasterModels.Tabla[]> ListarMAestrosAvanzadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/buscarMAvanzado", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/buscarMAvanzadoResponse")]
        MasterOfMasterModels.Tabla[] buscarMAvanzado(string pNombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/buscarMAvanzado", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/buscarMAvanzadoResponse")]
        System.Threading.Tasks.Task<MasterOfMasterModels.Tabla[]> buscarMAvanzadoAsync(string pNombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/buscarClavePrimaria", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/buscarClavePrimariaResponse")]
        string buscarClavePrimaria(string pNombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterOfMasterSvc/buscarClavePrimaria", ReplyAction="http://tempuri.org/IMasterOfMasterSvc/buscarClavePrimariaResponse")]
        System.Threading.Tasks.Task<string> buscarClavePrimariaAsync(string pNombreTabla);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterOfMasterSvcChannel : MasterOfMasterDesktop.svcMOM.IMasterOfMasterSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterOfMasterSvcClient : System.ServiceModel.ClientBase<MasterOfMasterDesktop.svcMOM.IMasterOfMasterSvc>, MasterOfMasterDesktop.svcMOM.IMasterOfMasterSvc {
        
        public MasterOfMasterSvcClient() {
        }
        
        public MasterOfMasterSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterOfMasterSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterOfMasterSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterOfMasterSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarMaestroDetalle(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle) {
            return base.Channel.InsertarMaestroDetalle(pMaestroDetalle);
        }
        
        public System.Threading.Tasks.Task<string> InsertarMaestroDetalleAsync(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle) {
            return base.Channel.InsertarMaestroDetalleAsync(pMaestroDetalle);
        }
        
        public string ActualizarMaestroDetalle(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle, string pDescripcionAntigua) {
            return base.Channel.ActualizarMaestroDetalle(pMaestroDetalle, pDescripcionAntigua);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMaestroDetalleAsync(MasterOfMasterModels.cMaestrosDetalle pMaestroDetalle, string pDescripcionAntigua) {
            return base.Channel.ActualizarMaestroDetalleAsync(pMaestroDetalle, pDescripcionAntigua);
        }
        
        public MasterOfMasterModels.cMaestrosDetalle[] ConsultarMaestroDetalle(long pIdMDetalle, long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal) {
            return base.Channel.ConsultarMaestroDetalle(pIdMDetalle, pIdMCabecera, pDescripcion, pIndActivo, pFechaInicial, pFechaFinal);
        }
        
        public System.Threading.Tasks.Task<MasterOfMasterModels.cMaestrosDetalle[]> ConsultarMaestroDetalleAsync(long pIdMDetalle, long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal) {
            return base.Channel.ConsultarMaestroDetalleAsync(pIdMDetalle, pIdMCabecera, pDescripcion, pIndActivo, pFechaInicial, pFechaFinal);
        }
        
        public string InsertarMaestroCabecera(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera) {
            return base.Channel.InsertarMaestroCabecera(pMaestroCabecera);
        }
        
        public System.Threading.Tasks.Task<string> InsertarMaestroCabeceraAsync(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera) {
            return base.Channel.InsertarMaestroCabeceraAsync(pMaestroCabecera);
        }
        
        public string ActualizarMaestroCabecera(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera, string pDescripcionAntigua) {
            return base.Channel.ActualizarMaestroCabecera(pMaestroCabecera, pDescripcionAntigua);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMaestroCabeceraAsync(MasterOfMasterModels.cMaestrosCabecera pMaestroCabecera, string pDescripcionAntigua) {
            return base.Channel.ActualizarMaestroCabeceraAsync(pMaestroCabecera, pDescripcionAntigua);
        }
        
        public MasterOfMasterModels.cMaestrosCabecera[] ConsultarMaestroCabecera(long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal) {
            return base.Channel.ConsultarMaestroCabecera(pIdMCabecera, pDescripcion, pIndActivo, pFechaInicial, pFechaFinal);
        }
        
        public System.Threading.Tasks.Task<MasterOfMasterModels.cMaestrosCabecera[]> ConsultarMaestroCabeceraAsync(long pIdMCabecera, string pDescripcion, System.Nullable<bool> pIndActivo, string pFechaInicial, string pFechaFinal) {
            return base.Channel.ConsultarMaestroCabeceraAsync(pIdMCabecera, pDescripcion, pIndActivo, pFechaInicial, pFechaFinal);
        }
        
        public string CrearTabla(MasterOfMasterModels.Tabla MA) {
            return base.Channel.CrearTabla(MA);
        }
        
        public System.Threading.Tasks.Task<string> CrearTablaAsync(MasterOfMasterModels.Tabla MA) {
            return base.Channel.CrearTablaAsync(MA);
        }
        
        public MasterOfMasterModels.Tabla[] ListarMAestrosAvanzados() {
            return base.Channel.ListarMAestrosAvanzados();
        }
        
        public System.Threading.Tasks.Task<MasterOfMasterModels.Tabla[]> ListarMAestrosAvanzadosAsync() {
            return base.Channel.ListarMAestrosAvanzadosAsync();
        }
        
        public MasterOfMasterModels.Tabla[] buscarMAvanzado(string pNombreTabla) {
            return base.Channel.buscarMAvanzado(pNombreTabla);
        }
        
        public System.Threading.Tasks.Task<MasterOfMasterModels.Tabla[]> buscarMAvanzadoAsync(string pNombreTabla) {
            return base.Channel.buscarMAvanzadoAsync(pNombreTabla);
        }
        
        public string buscarClavePrimaria(string pNombreTabla) {
            return base.Channel.buscarClavePrimaria(pNombreTabla);
        }
        
        public System.Threading.Tasks.Task<string> buscarClavePrimariaAsync(string pNombreTabla) {
            return base.Channel.buscarClavePrimariaAsync(pNombreTabla);
        }
    }
}
